<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="src\000-odcisk.jpg" />
    <None Remove="src\000-zdjecie.jpg" />
    <None Remove="src\111-odcisk.jpg" />
    <None Remove="src\111-zdjecie.jpg" />
    <None Remove="src\333-odcisk.jpg" />
    <None Remove="src\333-zdjecie.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="src\000-odcisk.jpg" />
    <Resource Include="src\000-zdjecie.jpg" />
    <Resource Include="src\111-odcisk.jpg" />
    <Resource Include="src\111-zdjecie.jpg" />
    <Resource Include="src\333-odcisk.jpg" />
    <Resource Include="src\333-zdjecie.jpg" />
  </ItemGroup>

</Project>
