<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="src\list.png" />
    <None Remove="src\paczka.png" />
    <None Remove="src\pocztowka.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="src\list.png" />
    <Resource Include="src\paczka.png" />
    <Resource Include="src\pocztowka.png" />
  </ItemGroup>

</Project>
